development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:88b4068653cfd3ce985db785acce45a9@sole.redistogo.com:9613/
  # channel_prefix: underneath_production
